name: musika

description: Musika app built with flutter

version: 1.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: ^0.13.2
  http: 0.12.0+2
  flare_flutter: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/gramophone.flr
    - assets/succes-check.flr
    - assets/error-check.flr