name: musika

description: Musika app built with flutter

version: 1.1.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: ^0.13.2
  http: 0.12.0+2
  flare_flutter: ^1.6.1
  flutter_launcher_icons: ^0.7.0
  font_awesome_flutter: ^8.0.1
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  google_sign_in: ^4.0.7
  flutter_facebook_login: ^3.0.0
  firebase_remote_config: ^0.2.0+7
  cloud_firestore: ^0.12.9+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.2
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/gramophone.flr
    - assets/succes-check.flr
    - assets/error-check.flr

flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/logo.png
  image_path_android: assets/logo.png
  adaptive_icon_background: assets/logo_background.png
  adaptive_icon_foreground: assets/logo_foreground.png